proyecto_noticias/app_proyecto/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app_proyecto'

urlpatterns = [
    path('cat_actualidad', views.actualidad, name='actualidad'),
    path('api_de_prueba/',views.api_de_prueba, name='api'),
    path('Bad_Bunny/', views.Bad_Bunny, name='Bad_Bunny'),
    path('cat_animales/', views.animales, name='animales'),
    path('cat_deportes/', views.deportes, name='deportes'),
    path('cat_ocio/', views.ocio, name='ocio'),
    path('cat_salud/', views.salud, name='salud'),
    path('cat_tecnologia/', views.tecnologia, name='tecnologia'),
    path('Confirmacion/', views.Confirmacion, name='confirmacion'),
    path('Contactanos/', views.Contacto, name='contacto'),
    path('dia_gato/', views.dia_gato, name='gato'),
    path('formulario/', views.Formulario, name='formulario'),
    path('hitman/', views.hitman, name='hitsman'),
    path('index/', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('narco_gato/', views.narco_gato, name='gato2'),
    path('NBA/', views.NBA, name='NBA'),
    path('noticia_nasa/', views.NASA, name='Nasa'),
    path('noticia_titanic/', views.noticia_titanic, name='titanic'),
    path('Noticia2/', views.Noticia2, name='noticia2'),
    path('ps5/', views.ps5, name='ps5'),
    path('registro/', views.registro, name='registro'),
    path('SALUD1/', views.SALUD1, name='salud'),
    path('salud2/', views.SALUD2, name='salud2'),
    path('salud3/', views.salud3, name='salud3'),
    path('switch/', views.switch, name='switch'),
    path('tecno1/', views.tecno1, name='tecno1'),
    path('tecno2/', views.tecno2, name='tecno2'),
    path('tecno3/', views.tecno3, name='tecno3'),
    path('Universidad_Catolica/', views.Universidad_Catolica, name='Cato'),
    path('Universidad_de_Chile/', views.Universidad_de_Chile, name='u_chile'),
    path('', views.index, name='home'),
    path('detalle/<int:pk>', views.PostDetailView.as_view(), name='detalle'),
    path('crear', views.post_crear, name='crear'),
]

proyecto_noticias/proyecto_noticias/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_proyecto.urls')),
    
]

proyecto_noticias/app_proyecto/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
# Create your models here.

class Noticias(models.Model):
    name = models.CharField(max_length=300 ) 
    categoria= models.CharField(max_length=40)
    description = models.CharField(max_length=300)

    def _str_(self):
        return self.name
    class Meta:
        db_table = 'Noticias'
        ordering = ['-id']


class Cliente (models.Model):
    name = models.CharField(max_length=300)
    telephone = models.IntegerField()
    email = models.EmailField(max_length= 100)


class Category(models.Model):
    name =models.CharField(max_length=300)
    featured = models.BooleanField(max_length=300, default=False)
    noticias = models.ManyToManyField(Noticias)
    cliente = models.ForeignKey(Cliente, on_delete=CASCADE)


    def _str_(self):
        return self.name
    class Meta:
        db_table = 'categories'
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        ordering = ['-id']

class Post(models.Model):
    autor = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)
    fecha_publicacion = models.DateTimeField(blank=True, null=True)
    imagen = models.FileField(blank=True, null=True, upload_to="app_proyecto")


    def publish(self):
        self.fecha_publicacion = timezone.now()
        self.save()

    def __str__(self):
        return self.titulo

proyecto_noticias/app_proyecto/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('titulo', 'contenido', 'imagen', 'fecha_publicacion','autor')
        widgets={ 
            'fecha_publicacion': forms.DateInput(attrs={'type':'date'}), 
            'autor':forms.HiddenInput()
            }


    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

proyecto_noticias/app_proyecto/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post
from django.utils import timezone
from django.urls import reverse
from .forms import PostForm
from django.views.generic import DetailView, ListView
# Create your views here.

def actualidad (request):
    return HttpResponse('actualidad.html', {})
def api_de_prueba(request):
    return render(request, 'app_proyecto/api_de_prueba.html',{})
def Bad_Bunny(request):
    return render(request, 'app_proyecto/Bad_Bunny.html',{})
def actualidad(request):
    return render(request, 'app_proyecto/cat_actualidad.html',{})
def animales(request):
    return render(request, 'app_proyecto/cat_animales.html',{})
def deportes(request):
    return render(request, 'app_proyecto/cat_deportes.html',{})
def ocio(request):
    return render(request, 'app_proyecto/cat_ocio.html',{})
def salud(request):
    return render(request, 'app_proyecto/cat_salud.html',{})
def tecnologia(request):
    return render(request, 'app_proyecto/cat_tecnologia.html',{})
def Confirmacion(request):
    return render(request, 'app_proyecto/Confirmacion.html',{})
def Contacto(request):
    return render(request, 'app_proyecto/Contactanos.html',{})
def dia_gato(request):
    return render(request, 'app_proyecto/dia_gato.html',{})
def Formulario(request):
    return render(request, 'app_proyecto/Formulario.html',{})
def hitman(request):
    return render(request, 'app_proyecto/hitman.html',{})
def index(request):
    return render(request, 'app_proyecto/index.html',{})
def login(request):
    return render(request, 'app_proyecto/login.html',{})
def narco_gato(request):
    return render(request, 'app_proyecto/narco.html',{})
def NBA(request):
    return render(request, 'app_proyecto/NBA.html',{})
def NASA(request):
    return render(request, 'app_proyecto/noticia_nasa.html',{})
def noticia_titanic(request):
    return render(request, 'app_proyecto/noticia_titanic.html',{})
def Noticia2(request):
    return render(request, 'app_proyecto/Noticia2.html',{})
def ps5(request):
    return render(request, 'app_proyecto/ps5.html',{})
def registro(request):
    return render(request, 'app_proyecto/registro.html',{})
def SALUD1(request):
    return render(request, 'app_proyecto/SALUD1.html',{})
def SALUD2(request):
    return render(request, 'app_proyecto/salud2.html',{})
def salud3(request):
    return render(request, 'app_proyecto/salud3.html',{})
def switch(request):
    return render(request, 'app_proyecto/switch.html',{})
def tecno1(request):
    return render(request, 'app_proyecto/tecno1.html',{})
def tecno2(request):
    return render(request, 'app_proyecto/tecno2.html',{})
def tecno3(request):
    return render(request, 'app_proyecto/tecno3.html',{})
def Universidad_Catolica(request):
    return render(request, 'app_proyecto/Universidad_Catolica.html',{})
def Universidad_de_Chile(request):
    return render(request, 'app_proyecto/Universidad_de_Chile.html',{})

class PostListView(ListView):
    model = Post
    template_name = "app_proyecto/api.html"


def post_lista(request):
    posts = None
    if request.user.is_authenticated:
        posts = Post.objects.all().order_by('fecha_publicacion')
    else:
        posts = Post.objects.filter(
            fecha_publicacion__lte=timezone.now()).order_by('fecha_publicacion')
    error = None
    if 'error' in request.session:
        error = request.session['error']
        del request.session['error']

    return render(request, 'app_proyecto/api.html', {'posts': posts, 'error': error})


def post_crear(request):
    if not request.user.is_authenticated:
        request.session['error'] = "Sin autorización para agregar nuevos post"
        return render(request, 'gestion_usuarios/login.html', {})

    if request.method == 'GET':
        post_form = PostForm(initial={'autor': request.user.pk})
        return render(request, 'app_proyecto/post_crear.html', {'post_form': post_form})
    elif request.method == 'POST':
        message = ""
        try:
            post_form = PostForm(data=request.POST)
            if post_form.is_valid():
                # post.fecha_publicacion = lambda fecha_publicacion : None if fecha_publicacion == "" else request.POST.get('fecha_publicacion')
                post = post_form.save()
                file = request.FILES['imagen']
                ext = file.name.split(".")[-1]
                file.name = str(post.pk) + "." + ext
                post.imagen = file
                post.save()
                message = "la publicacion fue guardada"
                return HttpResponseRedirect(reverse('app_proyecto:detalle', args=(post.pk,)))
            else:
                message = post_form.errors
                return render(request, 'app_proyecto/post_crear.html', {'message': message, 'post_form': post_form})
        except Exception as e:
            message = "Error al guardar la publicación: " + str(e)
            return render(request, 'app_proyecto/post_crear.html', {'message': message})
    else:
        response = HttpResponse('Método no permitido')
        response.status_code = 405
        return response


class PostDetailView(DetailView):
    model = Post
    template_name = "app_proyecto/post_detalle.html"
    


def post_detalle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        post.publish()

    try:
        return render(request, 'app_proyecto/post_detalle.html', {'post': post})
    except Exception as e:
        response = HttpResponse("Error al guardar la publicación: " + str(e))
        response.status_code = 404
        return response

proyecto_noticias/app_proyecto/templates/app_proyecto/Bad_Bunny.html
{% load static %}
<!DOCTYPE html>
<html>
  <head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    
    <title>CAOS NEWS-Actualidad</title>
  </head>
  <body>
     <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/index">
        <img src="{% static 'IMG/Caos news.png' %}" width="50" height="30" class="d-inline-block align-top" alt="" >
        CAOS NEWS  
      </a>
          <form style class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
          </form> 
    </nav>
    <div style="border: black 3px solid;" class="nav-scroller py-1 mb-2">
      <nav class="nav d-flex justify-content-between">
        <a class="p-2 text-muted" href="/cat_actualidad">Actualidad</a>
        <a class="p-2 text-muted" href="/cat_animales">Animales</a>
        <a class="p-2 text-muted" href="/cat_deportes">Deportes</a>
        <a class="p-2 text-muted" href="/cat_salud">Salud </a>
        <a class="p-2 text-muted" href="/cat_tecnologia">Tecnologia</a>
        <a class="p-2 text-muted" href="/cat_ocio">Ocio</a>
        <a class="p-2 text-muted" href="/api_de_prueba">Internacional</a>
      </nav>
    </div>
    </nav>
    <hr>
    <h4 class="categoria" style="margin-left: 50px; margin-right: 50px;">-Actualidad</h4>
    <hr>
    <h1  class="titular" style="margin-right: 50px;margin-left: 50px;"> El gran debut de Bad Bunny en la WWE: participará en el evento más importante de la lucha libre</h1>
    <br>
    <hr>
    <h4 class="autor" style="margin-left: 50px;margin-right: 50px;">Diana Aros<br>
        <p class="card-text"><small class="text-muted"> actualizado 10 abril 2021</small></p>
       <img src="{% static 'IMG/bad bunny3.jpg' %}" width="800px" height="300px" alt="portada gato" style="vertical-align:middle;margin: 100px 100px">
    </p>
    <div class="col-md-8"></div>
      <div class="card-body">
        <h5 class="card-title">BAD BUNNY</h5>

        <p class="card-text"><small class="text-muted">
            No es desconocido que el cantante puertorriqueño Bad Bunny vive uno de sus mejores momentos de su carrera. Y es el artista de 27 años no sólo ha logrado conquistar la industria de la música, sino que ahora lo está haciendo en la industria del entretenimiento deportivo.
            A principios de este año, la WWE confirmaba el fichaje del cantante y según la revista Forbes, el presidente y director de ventas de la WWE, Nick Khan, explicó que “Bad Bunny es una estrategia diseñada para a una audiencia joven. Estamos reevaluando nuestra estrategia de mercado y próximamente también lanzaremos producto para niños entre 2 y 6 años”.
            Su primera aparición fue en el pasado Royal Rumble, donde cantó la canción ‘Booker T’ junto al luchador del mismo nombre.
        </small></p>

        <img src="{% static 'IMG/badbunny2.jpg' %}" width="800px" height="300px" alt="portada gato" style="vertical-align:middle;margin: 100px 100px">
                
        <P><p class="card-text"><small class="text-muted">
            Ahora, el puertorriqueño se presentará en el evento más grande de la lucha libre profesional, WrestleMania 37, donde el cantante ya se prepara y entrena para el duelo que será por parejas: Priest y Bunny contra Miz y Morrison.
            Entre aparición y aparición, Bad Bunny ha entrenado duro para poder ofrecer un buen espectáculo.La pelea se realizará el sábado 10 de abril, durante la primera jornada de Wrestlemania, que tendrá como lucha estelar la de Bobby Lashley contra Drew McIntyre por el Campeonato de la WWE.

        </small></p></P>
      </div>
    </div>
</body>
</html> 

proyecto_noticias/app_proyecto/templates/app_proyecto/NBA.html
{% load static %}
<!DOCTYPE html>
<html>
  <head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
    <title>CAOS NEWS-Deporte</title>
  </head>
  <body>
     <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/index">
        <img src="{% static 'IMG/Caos news.png' %}" width="50" height="30" class="d-inline-block align-top" alt="" >
        CAOS NEWS  
      </a>
          <form style class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
          </form> 
    </nav>

    <div style="border: black 3px solid;" class="nav-scroller py-1 mb-2">
      <nav class="nav d-flex justify-content-between">
        <a class="p-2 text-muted" href="/cat_actualidad">Actualidad</a>
        <a class="p-2 text-muted" href="/cat_animales">Animales</a>
        <a class="p-2 text-muted" href="/cat_deportes">Deportes</a>
        <a class="p-2 text-muted" href="/cat_salud">Salud </a>
        <a class="p-2 text-muted" href="/cat_tecnologia">Tecnologia</a>
        <a class="p-2 text-muted" href="/cat_ocio">Ocio</a>
        <a class="p-2 text-muted" href="/api_de_prueba">Internacional</a>
      </nav>
    </div>
    </nav>  
    <hr>
    <h4 class="categoria" style="margin-right: 50px;margin-left: 50px;">NEWS-Deportes</h4>
    <hr>
    <h1 class="titular" style="margin-right: 50px;margin-left: 50px;"> "Fui arquero de la UC": el capítulo más desconocido del chileno que apunta a la NBA</h1>
    <hr>
    <h4 class="autor" style="margin-right: 50px;margin-left: 50px;">Pablo Vera / Daniel Tobar<br>
        <p class="card-text"><small class="text-muted"> Actualizado a: 17 de abril de 2021</small></p>
       <img src="{% static 'IMG/nba_deportes.jpg' %}" width="800px" height="300px" alt="Universidad_Catolica" style="vertical-align:middle;margin: 100px 100px">
    </p>
    <div class="col-md-8"></div>
      <div class="card-body">
        <h5 class="card-title">Nicolás Carvacho, basquetbolista que brilla en Bulgaria y que tiene opciones de llegar a la NBA.</h5>

        <p class="card-text"><small class="text-muted">
            Nació en Chile, pero luego se fue a vivir a Estados Unidos, la tierra de su madre. Sin embargo, la conexión con nuestro país es bastante profunda: defiende a la Roja y en su adolescencia vivió por un tiempo en Santiago. 
            En ese tiempo, su carrera como deportista pudo cambiar por completo.
            <br>
            <br>
            "Es una historia divertida. Fui a Chile por seis meses cuando tenía 15 años para jugar fútbol como arquero en Universidad Católica y me encantó. Mis padres han vivido en Estados Unidos durante toda mi vida, pero en esa época tomé la decisión de que mi deporte sería el fútbol. Decidí jugar en Chile, porque en Estados Unidos el fútbol está creciendo, pero no está al nivel de pasión que la gente tiene allá por el fútbol", cuenta en diálogo con As.
            ¿Qué pasó entonces? "Luego de ese período en Santiago volví a Estados Unidos durante el período de vacaciones de Navidad y fui a ver un partido de básquetbol en mi antiguo colegio. Ahí dije '¿saben qué? Ahora voy a jugar básquetbol'. Supongo que tomé la decisión correcta, mirar ese partido cambió mi vida entera", recuerda.

        </small></p>
      </div>
    </div>
</body>
</html> 

proyecto_noticias/app_proyecto/templates/app_proyecto/Universidad_De_Chile.html
{% load static %}
<!DOCTYPE html>
<html>
  <head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
    <title>CAOS NEWS-Deporte</title>
  </head>
  <body>
     <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/index">
        <img src="{% static 'IMG/Caos news.png' %}" width="50" height="30" class="d-inline-block align-top" alt="" >
        CAOS NEWS  
      </a>
          <form style class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
          </form> 
    </nav>

    <div style="border: black 3px solid;" class="nav-scroller py-1 mb-2">
      <nav class="nav d-flex justify-content-between">
        <a class="p-2 text-muted" href="/cat_actualidad">Actualidad</a>
        <a class="p-2 text-muted" href="/cat_animales">Animales</a>
        <a class="p-2 text-muted" href="/cat_deportes">Deportes</a>
        <a class="p-2 text-muted" href="/cat_salud">Salud </a>
        <a class="p-2 text-muted" href="/cat_tecnologia">Tecnologia</a>
        <a class="p-2 text-muted" href="/cat_ocio">Ocio</a>
        <a class="p-2 text-muted" href="/api_de_prueba">Internacional</a>
      </nav>
    </div>
    </nav>  
    <hr>
    <h4 class="categoria" style="margin-right: 50px;margin-left: 50px;">NEWS-Deportes</h4>
    <hr>
    <h1 class="titular" style="margin-right: 50px;margin-left: 50px;"> De Paul: "Es difícil mantenerse al margen de todo lo que se habla"</h1>
    <hr>
    <h4 class="autor" style="margin-right: 50px;margin-left: 50px;">Universidad de Chile<br>
        <p class="card-text"><small class="text-muted"> Actualizado a: 15 de abril de 2021</small></p>
       <img src="{% static 'IMG\deportes_universidad_de_chile.jpg' %}" width="800px" height="300px" alt="Universidad_De_Chile" style="vertical-align:middle;margin: 100px 100px">
    </p>
    <div class="col-md-8"></div>
      <div class="card-body">
        <h5 class="card-title">
            El portero de la U confesó que es complicado trabajar preocupado de cuestiones extrafutbolísticas. 
            También habló sobre cómo ha visto a Dudamel.</h5>

        <p class="card-text"><small class="text-muted">
            Fernando de Paul compareció ante los medios en el Centro Deportivo Azul y se refirió principalmente a cómo se trabaja considerando todos los problemas que han aquejado al club en las últimas semanas, desde el pobre rendimiento exhibido en el Campeonato Nacional, las polémicas de Rafael Dudamel y los contagios de Covid-19.
            'Tuto' confesó que es complejo aislarse de las cuestiones extrafutbolísticas: "Es difícil mantenerse al margen de todo lo que se habla. Por más que uno no consuma redes sociales o televisión, inevitablemente se escucha todo. Pero somos profesionales, tenemos que enfocarnos en cada entrenamiento y partido. Estamos, o deberíamos estar preparados para este tipo de situaciones. Más sabiendo que estamos en un club grande, donde las cosas repercuten más que en otros lados".


        </small></p>

        <img src="{% static 'IMG/u de chilee.jpg' %}" width="800px" height="300px" alt="portada gato" style="vertical-align:middle;margin: 100px 100px">

        <P><p class="card-text"><small class="text-muted">
            Otras declaraciones de Fernando de Paul
            ¿Cómo ve a Dudamel?: "Lo veo bien, con la misma exigencia hacia nosotros de un principio. Él es la cabeza de este grupo entonces no puede demostrar debilidad ni mucho menos, porque sino sería difícil trabajar así. Lo veo muy bien, enfocado en lo que tiene que hacer, y su cuerpo técnico lo está apoyando como siempre".
            <br>
            <br>
            ¿Mejoró la U?: "Creo que sí. El otro día ante La Serena no ganamos por un error puntual que escapa de nuestros manos, pero mejoramos mucho en relación al partido contra Huachipato. Todavía falta pero hay que seguir así".
            <br>
            <br>
            ¿Falta liderazgo en el club?: "En el último tiempo no hemos conseguido los resultados que requiere esta institución, todo se suma y llegan las críticas. Sobre mi poca experiencia, porque hace un par de años que estoy en la institución y tampoco tengo un recorrido enorme, creo que cada uno se tiene que hacer cargo del lugar que ocupa. El futbolista tiene que estar preocupado de jugar el fútbol, el cuerpo médico tiene su trabajo, los directores también, y así. Lo importante acá es la U, no las personas que estamos de paso".
            <br>
            <br>
            Partido contra Unión Española: "Los dos estamos muy necesitados de un triunfo. Será un partido difícil, tienen grandes individualides que si funcionan como equipo es aún más difícil. Estamos enfocados en lo que tenemos que hacer. Hay que seguir mejorando y trataremos de afinar para conseguir el primer triunfo del campeonato.
            <br>
            <br>
            Cambios en defensa: "Terminamos muy bien en lo defensivo el año pasado. Hablo de todos, desde el primer delantero. El otro día hicimos mucha presión arriba y eso evita que te lleguen a tu arco. Si bien llegaron jugadores nuevos como Ramón (Arias), Yonathan (Andía), también Marcelo (Morales), creo que lo hemos hecho bien. Ante Huachipato nos anotaron solo un gol y el otro día pudimos mantener el cero.
            <br> 
            </small></p></P>
      </div>
    </div>
</body>
</html> 

proyecto_noticias/app_proyecto/templates/app_proyecto/post_crear.html
{% load static %}
{% extends "subir_noticias.html" %}

{% block content %}

<a href="{% url 'app_proyecto:api' %}">Volver a la lista</a>
<div>
    {{ message }}
</div>
<br>
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <label>
        Autor
    </label>
    {{ request.user.username }}
    
    {{ post_form.as_p }}
    
    <button type="submit">Crear post</button>

</form>


{% endblock content %}